In [2]:
import cv2

In [26]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

img = cv2.imread("C://Users//hugoh//Desktop//FaceDeteaction//faces2.jpg",1)

gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.07,minNeighbors =5)

print(type(faces))
print(faces) 

for x,y,w,h in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)

cv2.imshow("Gray", img)

#resized = cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0])))

cv2.waitKey(0)

cv2.destroyAllWindows()



<class 'numpy.ndarray'>
[[531 319  60  60]
 [422 151 146 146]
 [131 118 113 113]
 [379 380 166 166]
 [242 426  71  71]
 [577 196 217 217]]
